### ISSUE TITLE
Version 0.6.1 cannot be enabled

### ISSUE THREAD

**Issue by Ezalor** [apsun/NekoSMS#11]
although enabled in Xposed Installer, it keeps alert to enable it

**Comment by apsun** [comment]
Whoops! My bad, it seems ProGuard went a bit overboard and deleted the Xposed module classes. This issue was present in version 0.6 as well. I'll upload a fixed APK in a bit.

**Comment by apsun** [comment]
This issue is now fixed in version 0.6.2. The new version has been pushed to the Xposed module repository, or you can download it here: https://github.com/apsun/NekoSMS/releases/tag/0.6.2

Apologies for the inconvenience!

**Comment by Ezalor** [comment]
Tested, works well! Thanks!
Very useful and powerful app, many thanks for your efforts!
