### ISSUE TITLE
about the import/export feature

### ISSUE THREAD

**Issue by SIC4RIUS** [apsun/NekoSMS#22]
This is the first time I use your NecoSMS, I think it would be real neat if there is an import/export function, because I have five phones in hand. Not that I use them all, but it would be nice to let all of them to have NecoSMS. It would save me considerable about of time, don't you agree, mate?

**Comment by apsun** [comment]
Actually the import/export feature was removed in 0.10 for another planned feature which was later canceled. (unlucky first time user, eh? :-p)

That said, I have gotten a few requests to add it back, so I'll work on it. Sorry for any inconvenience.

**Comment by apsun** [comment]
Import/export support has been (re-)added in 0.11.0.
