### ISSUE TITLE
Sms still showing in Google Messenger

### ISSUE THREAD

**Issue by spopinski** [apsun/NekoSMS#23]
Using latest version of NekoSMS, official MM for Z3 Dual D6633 and latest xposed.

Neko app showing filtered sms both in the app and messenger app.

**Comment by apsun** [comment]
If it shows up in your blocked SMS list within NekoSMS, the Xposed module is probably malfunctioning. Please post your Xposed log (Xposed Installer -> Logs -> Save to SD card).

**Comment by spopinski** [comment]
Here is tge logs

06-06 17:12:54.286 I/Xposed  (  650): -----------------
06-06 17:12:54.286 I/Xposed  (  650): Starting Xposed version 85, compiled for SDK 23
06-06 17:12:54.286 I/Xposed  (  650): Device: D6633 (Sony), Android version 6.0.1 (SDK 23)
06-06 17:12:54.286 I/Xposed  (  650): ROM: 23.5.A.0.575
06-06 17:12:54.286 I/Xposed  (  650): Build fingerprint: Sony/D6633/D6633:6.0.1/23.5.A.0.575/1719295681:user/release-keys
06-06 17:12:54.286 I/Xposed  (  650): Platform: armeabi-v7a, 32-bit binary, system server: yes
06-06 17:12:54.286 I/Xposed  (  650): SELinux enabled: yes, enforcing: no
06-06 17:12:57.697 I/Xposed  (  650): -----------------
06-06 17:12:57.698 I/Xposed  (  650): Added Xposed (/system/framework/XposedBridge.jar) to CLASSPATH
06-06 17:12:57.979 I/Xposed  (  650): Detected ART runtime
06-06 17:12:58.011 I/Xposed  (  650): Found Xposed class de/robv/android/xposed/XposedBridge, now initializing
06-06 17:12:58.329 I/Xposed  (  650): Loading modules from /data/app/com.crossbowffs.nekosms-1/base.apk
06-06 17:12:58.514 I/Xposed  (  650):   Loading class com.crossbowffs.nekosms.xposed.SmsHandlerHook
06-06 17:12:58.530 I/Xposed  (  650):   Loading class com.crossbowffs.nekosms.xposed.XposedUtilsHook
06-06 17:12:58.530 I/Xposed  (  650): Loading modules from /data/app/org.ast11.hidesimicons-1/base.apk
06-06 17:12:58.604 I/Xposed  (  650):   Loading class org.ast11.hidesimicons.HideSimIcons
06-06 17:12:58.612 I/Xposed  (  650): Loading modules from /data/app/com.jt5.xposed.chromepie-1/base.apk
06-06 17:12:58.658 I/Xposed  (  650):   Loading class com.jt5.xposed.chromepie.ChromePie
06-06 17:13:21.627 I/Xposed  ( 5926): HideSimIcon: Detected Marshmallow 6.0, hiding spacer
06-06 17:13:58.078 I/Xposed  ( 9982): HideSimIcon: Detected Marshmallow 6.0, hiding spacer
06-06 17:20:34.638 I/Xposed  ( 4157): HideSimIcon: Detected Marshmallow 6.0, hiding spacer
06-06 17:31:22.589 I/Xposed  (25400): HideSimIcon: Detected Marshmallow 6.0, hiding spacer

**Comment by apsun** [comment]
I don't see anything problematic in your logs. Can you post the logs again after receiving an SMS?

Also, just a thought - if you are sending a message to yourself for testing, try sending it from a different phone -- I know some SMS apps behave strangely if you send a message to yourself.

**Comment by spopinski** [comment]
Ah! It's working when I tried from another phone!

Sorry to bugs you. Please consider this closed.

Thank you for the awesome module.

**Comment by apsun** [comment]
No problem! Glad it's working for you! :-)
