### ISSUE TITLE
0.12 wishlist

### ISSUE THREAD

**Issue by apsun** [apsun/NekoSMS#24]
High priority
---

- [x] Whitelist support
  - Whitelist rules should always come before blacklist rules (no manual sorting)
- [ ] Support Android N
  - Make sure Xposed module works, obviously
  - ~~Support new partial external storage write permissions~~
    - [Doesn't support non-standard directories, WTF Google.](https://developer.android.com/reference/android/os/storage/StorageVolume.html#createAccessIntent(java.lang.String))

Medium priority
---

- [ ] ~~Multi-SIM support (Android 5.1+)~~
  - Restoring messages to inbox should associate with the correct SIM card
  - **Multi-SIM API (`getSubId()`) is not public, I would rather not rely on implementation details**
- [x] Contact whitelist setting
  - Option to whitelist all numbers in the user's contact list
  - Only works if phone process can read contacts (pretty sure it can)
- [ ] ~~Filter rule/blocked message multi-select~~
  - For batch-deleting things
  - **Too much effort for little gain. Maybe in a future release.**
- [x] FAB + Snackbar interaction fix
  - If FAB is hidden and Snackbar is shown, FAB state becomes out of sync

Low priority
---

- [ ] ~~Per-rule enable/disable toggle~~
  - For debugging filters, maybe?
  - **This would require restructuring the way data is passed between the module and the app receiver. Not worth the additional effort.**
- [ ] ~~Per-rule notification settings~~
  - Make some "maybe-spam" messages still show notifications, hard-ignore the rest
  - **See above.**
- [x] Option to set startup fragment
  - No idea why anyone would want to look at blocked messages all the time, but okay
  - **Possible alternative: save the current fragment on exit, open to same fragment**

**Comment by kukki** [comment]
Vote for Whitelist support

**Comment by apsun** [comment]
0.12.0 released. Should be compatible with Android N in theory, but I don't have any test devices, so it may require another update when that gets released.
