### ISSUE TITLE
Force close on restore message

### ISSUE THREAD

**Issue by garoxas** [apsun/NekoSMS#25]
Hi,
Just want to report a bug that occurs when NekoSMS tries to restore all messages
I'm using Samsung Galaxy S7 edge (Android 6.0.1, NekoSMS 0.12.2)

Here's the logcat dump

> 09-06 21:34:05.711 16286 16286 D AndroidRuntime: Shutting down VM
09-06 21:34:05.711 16286 16286 E AndroidRuntime: FATAL EXCEPTION: main
09-06 21:34:05.711 16286 16286 E AndroidRuntime: Process: com.crossbowffs.nekosms, PID: 16286
09-06 21:34:05.711 16286 16286 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.os.Parcel.readException(Parcel.java:1626)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:183)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.database.DatabaseUtils.readExceptionFromParcel(DatabaseUtils.java:135)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.content.ContentProviderProxy.insert(ContentProviderNative.java:476)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.content.ContentResolver.insert(ContentResolver.java:1284)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.crossbowffs.nekosms.loader.InboxSmsLoader.writeMessage(InboxSmsLoader.java:31)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.crossbowffs.nekosms.app.BlockedMessagesFragment.restoreSms(BlockedMessagesFragment.java:250)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.crossbowffs.nekosms.app.BlockedMessagesFragment.access$200(BlockedMessagesFragment.java:27)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.crossbowffs.nekosms.app.BlockedMessagesFragment$3.onClick(BlockedMessagesFragment.java:204)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.support.v7.app.AlertController$ButtonHandler.handleMessage(AlertController.java:157)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:102)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:158)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7229)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
09-06 21:34:05.711 16286 16286 E AndroidRuntime:        at de.robv.android.xposed.XposedBridge.main(XposedBridge.java:102)
09-06 21:34:05.711  5274  5567 W ActivityManager:   Force finishing activity com.crossbowffs.nekosms/.app.MainActivity

Thanks for your awesome app

**Comment by apsun** [comment]
Weird. Looks like it might be this bug with Samsung devices: http://stackoverflow.com/questions/32603119/adding-a-contact-group-gives-nullpointerexception-on-htc-and-samsung-devices

I'll upload a build which hopefully fixes this problem later today. Thanks for the report.

**Comment by apsun** [comment]
Hopefully fixed in 4639e8c0b17a43f5b552b2aef71cc4d7dfe98fef.

Can you try out this build to see if it works? I don't have a Samsung device to test on. [NekoSMS-release.zip](https://github.com/apsun/NekoSMS/files/460367/NekoSMS-release.zip)

**Comment by garoxas** [comment]
Great, it works now
Thanks a lot for your prompt fix
