### ISSUE TITLE
SMS messages being restored to wrong SIM card

### ISSUE THREAD

**Issue by 1576186685** [apsun/NekoSMS#27]
when there are two sim card, restoring the blocked message will lose the information which sim the message is sent to. hope you can understand my chinese English.
嗯，，希望你也能懂中文。双卡手机，恢复出被拦截短信的时候，短信所属的卡的信息没了。无法区分是卡一的短信还是卡二的短信。

**Comment by apsun** [comment]
支持这个功能倒是不难，主要的问题是我没有双卡机所以无法测试。。要是愿意帮测试的话可以出个beta版

Your English is fine ;-)

**Comment by apsun** [comment]
Try out this build: [NekoSMS-release.zip](https://github.com/apsun/NekoSMS/files/568265/NekoSMS-release.zip)

You should back up all your data first just in case, I haven't tested it at all.

This only works on new blocked messages. Old messages from the previous version will still be restored to the default SIM card.

**Comment by 1576186685** [comment]
tested. it works just fine. thanks a lot. happy to do a beta-testing job (…). didn't expect the APP without ads and support options to update so fast. thanks for your efforts. 
双卡机上测试了，恢复后能显示SIM卡。也没有数据丢失。自己也算小半个测试人员了吧，想起来还蛮开心：)小而强大的插件，连捐赠选项都没有，还能这么及时的维护。必须赞^_^

**Comment by apsun** [comment]
Glad it works! :-)

Fixed in commit 5305486a16202a086a8f1307c9e0e92b3c5b99d6.
