### ISSUE TITLE
two simcards problem

### ISSUE THREAD

**Issue by medicamin** [apsun/NekoSMS#29]
I Updated yesterday to version 0.13.0
in Huawei honor 3c build 320, Android 4.4.2, when sms received from simcard No.2 it restores to simcard No.1 . Changelog says it's solved, but I see this problem here.

Thanks

**Comment by apsun** [comment]
NekoSMS only handles multi-SIM on Android 5.1+ (that's when the feature was added to AOSP). All multi-SIM phones on 5.0 or below have a custom implementation, which would be too much effort to support.

I've updated the changelog to reflect this. Sorry for the inconvenience.
