### ISSUE TITLE
LOL USB

### ISSUE THREAD

**Issue by Zonglin-Li6565** [apsun/NekoSMS#32]
Write your issue description here.

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device ("Nexus 6P"): 
- Android version ("7.1.1"): 
- Xposed version ("53"): 
- NekoSMS version ("0.13.1"): 

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
```do {```
![genius](https://cloud.githubusercontent.com/assets/14020276/26417605/4e16ae94-407f-11e7-8e22-c2fde7da8ca0.png)
```} while (u->sb);```
