### ISSUE TITLE
Android 7+的xposed好像遥遥无期，作者能考虑从magisk入手解决吗？

### ISSUE THREAD

**Issue by iVeego** [apsun/NekoSMS#34]
不是很懂底层技术，算是小白问题，谢谢。

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by apsun** [comment]
Magisk的作用是替换系统文件，而Xposed的作用是在运行时修改代码。所以说就算有了Magisk也是需要Xposed的，光用Magisk是做不到的。

**Comment by iVeego** [comment]
@apsun 谢谢～

_Sent from my OnePlus ONEPLUS A3010 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by ffftwo** [comment]
[https://github.com/RikkaApps/Riru.git](url) 

@apsun 不知道能否通过这个magisk模块来实现

以前装xposed就只为短信过滤这一个功能，现在xposed也装不了就只剩绝望了

**Comment by apsun** [comment]
@ffftwo Riru looks like a native code hooking mechanism, have you tried Edxposed as suggested in #58? It's built on top of Riru apparently.
