### ISSUE TITLE
Android O support

### ISSUE THREAD

**Issue by apsun** [apsun/NekoSMS#36]
- [x] Xposed module compatibility (duh!)
- [x] Adaptive icons (launcher, app shortcuts)
- [x] Fix double-notification bug

**Comment by apsun** [comment]
As it turns out, Android O seems to have removed the *_SMS permissions from `com.android.phone`, which means we can no longer protect our blocked messages/filters database using that permission. Using any other permission seems like an ugly hack, so here are the alternatives:

1. Use `getCallingPackage()` to limit the callers to just `com.android.phone`. Seems like an ugly hack, but it should work.

2. Refactor the blocking logic out of the module and into a service that runs under the NekoSMS app. Blocking can be done by sending a broadcast, just like it did on Android 4.3 and below. I would prefer this option, but it would be a significant change and I will have difficulty testing it across the various supported Android versions. Also, it's more brittle to future changes in the phone process.

My proposal: go with option (1) for now, but work on (2) in a future NekoSMS version

**Comment by apsun** [comment]
(2) also has the added benefit of removing a lot of ugly complexity in the app. We can finally implement verbose logging in a reasonable way (global singleton, anyone?), and get rid of the `BroadcastListener` in `SmsFilterLoader`. Oh, and we won't need `RemotePreferences` anymore.

Ideally I would also like to get rid of the `grantWriteSmsPermissions` portion of the Xposed module, since that's just waiting to get broken by a future Android update. Don't know of a suitable alternative at the time, though.

**Comment by apsun** [comment]
Method (1) implemented in 6888eb7b8ea4a9cd735617eacd89c3e6d87c925e

**Comment by apsun** [comment]
For method (2), I believe replacing the dispatchIntent hook with something like this should work:

```
Intent originalIntent = new Intent(intent);
intent.addFlags(Intent.FLAG_RECEIVER_FOREGROUND);
mContext.sendOrderedBroadcast(intent,
    "com.crossbowffs.nekosms.permission.BLOCK_SMS",
    new BroadcastReceiver() {
        @Override
        public void onReceive(Context context, Intent intent) {
            if (getResultCode() == Activity.RESULT_CANCELED) {
                // discard SMS and clean up database
            } else {
                // re-call dispatchIntent with originalIntent (avoiding this hook somehow)
            }
        }
    },
    (Handler)XposedHelpers.callMethod(param.thisObject, "getHandler"),
    Activity.RESULT_OK, null, null);
```

**Comment by lixingcong** [comment]
NekoSMS works fine on my Oneplus3T

LineageOS 15.1 + xposed 90beta3

**Comment by raamee** [comment]
Thank you lixingcong. This is the only module that made me to wait and not to switch to Oreo. I will try upgrade to Oreo soon and will let you know.

**Comment by raamee** [comment]
Upgraded to 8.1 Oreo and it works fine.

**Comment by HankAviator** [comment]
above probably was a miscall.
