### ISSUE TITLE
黑名单关键词设置后无效

### ISSUE THREAD

**Issue by iVeego** [apsun/NekoSMS#38]
Write your issue description here.
黑名单设置文本关键词后无效
---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: OnePlus 3T
- Android version: 7.1.1
- Xposed version: V88
- NekoSMS version: 0.15.0

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
10-11 12:24:33.228 E/Xposed  ( 2232): NekoSMS: Failed to read preference: pref_enable
10-11 12:24:33.229 I/Xposed  ( 2232): NekoSMS: Received a new SMS message
10-11 12:24:33.231 E/Xposed  ( 2232): NekoSMS: Failed to read preference: pref_whitelist_contacts
10-11 12:24:33.231 I/Xposed  ( 2232): NekoSMS: Cached SMS filters dirty, loading from database
10-11 12:24:33.232 E/Xposed  ( 2232): NekoSMS: Failed to load SMS filters (queryAll returned null)
10-11 12:24:33.232 I/Xposed  ( 2232): NekoSMS: Allowed message (matched whitelist or no matching rules)
```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
有没有安装阻止运行之类的软件？一加手机好像自带这个功能，试试把NekoSMS加到白名单上。

**Comment by iVeego** [comment]
@apsun 加入白名单后OK了，多谢。
