### ISSUE TITLE
插件在xp v88.2上失效

### ISSUE THREAD

**Issue by kingfanslwh** [apsun/NekoSMS#39]
反馈个#nekosms 0.15的bug，在v88.2框架下，好像不能识别添加的规则，看日志插件是正常启动着。如果可以的话，希望你能有空看看
---
- Device: sagit(Mi6)
- Android version: 7.1.2
- Xposed version: v88.2
- NekoSMS version: 0.15.0

```
 nekosms规则文件和xp日志我打包了。

[nekosms.zip](https://github.com/apsun/NekoSMS/files/1464754/nekosms.zip)






```

 酷安上也有好多酷友反馈用不了。。。

**Comment by apsun** [comment]
你在用wildcard匹配方式，这个不支持 `|`，只能用 `*` 和 `?` 。https://github.com/apsun/NekoSMS/wiki/Filter-rules#wildcard-mode

想用 `|` 的话需要用正则表达式。或者你就再创建个规则，像这样：

![screenshot_20171112-105536](https://user-images.githubusercontent.com/14020276/32701282-46a1586c-c798-11e7-83e8-aaf4dae028af.png)

**Comment by kingfanslwh** [comment]
嗯，我按照你说的修改成功了。
