### ISSUE TITLE
是否考虑增加不需要xposed的模式？

### ISSUE THREAD

**Issue by ipcjs** [apsun/NekoSMS#40]
xposed对新系统的支持很慢，Android官方的短信应用又没有垃圾短信过滤功能，第三方应用，像国内的又很流氓。感觉一个简单地，不需要xposed模块的短信过滤应用很有必要。

我设想了一种模式：要求用户关掉默认短信应用的通知，由NekoSMS来弹通知。
正常短信直接弹通知（如果可以的话，还可以做个简单的快速回复功能）；
需要屏蔽的短信，不通知；

因为权限原因，不能做到删除垃圾短信，但我感觉，只要做到垃圾短信不弹通知，就足够了。

按照上面的思路，我试着修改了下代码，能用，感觉还行😅

作者是否考虑让NekoSMS增加这样的模式？
是否接收实现这样的功能的PR？

**Comment by apsun** [comment]
我感觉这样不是很完美，拦截应该包括删除的功能。要删除信息的话必须改默认短信app，而且那样就不能从真正的短信app发信息，很烦恼

还有个问题就是每个app处理intent的方法不一样，点通知打开app这样可能会需要一个一个handle

暂时我觉得还是需要Xposed最好，没有那么多compromise，无论用的是哪个app都支持

**Comment by ipcjs** [comment]
删除功能，权限不够，没办法的事。
从我自己的角度来看，垃圾短信，只要不弹通知，不打挠到我，影响也不大。

至于点击通知打开app功能，你是指点击通知，直接跳转到短信app的回复界面吗？
这大概只能一个个适配了，不过，会用NekoSMS的人，十有八九是原生党，其实上只要适配几个官方app就没什么大问题了。剩下的app直接跳转到它们主页，就是了，不管它😅

另外我们可以做个直接在通知栏回复的功能，我记得发短信的权限是可以获取到的。这样基本上就不怎么需要跳转了。

xposed好是好，但每次升到最新的系统，就用不了，基本对android系统的支持会晚一年。。。

**Comment by apsun** [comment]
> 从我自己的角度来看，垃圾短信，只要不弹通知，不打挠到我，影响也不大。

For me it's actually the opposite, the annoying part is deleting the messages. I want to have a clean inbox; if I have to manually delete the spam then there's a chance I'll accidentally delete some important messages I want to keep.

> 其实上只要适配几个官方app就没什么大问题了。剩下的app直接跳转到它们主页，就是了，不管它

That goes against one of the goals of this project, which is to have an SMS blocker that [doesn't care what SMS app you use](https://github.com/apsun/NekoSMS#does-nekosms-work-with-insert-sms-app-here). 

> xposed好是好，但每次升到最新的系统，就用不了，基本对android系统的支持会晚一年。。。

Given the [Android market share](https://developer.android.com/about/dashboards/index.html) right now, I wouldn't worry too much about that...

Sorry for using English, my IME is broken on Linux right now.

**Comment by ccaapton** [comment]
github上还有不少开源的质量不错的sms程序比如smsdroid/qksms，能否考虑提供一个IoC接口，把nekosms做成插件，然后由其他app来调用nekosms做出是否屏蔽的判断？

**Comment by apsun** [comment]
If you use those as your default SMS application, then they can just block the messages themselves. NekoSMS is only useful when your default SMS app doesn't support blocking. If they want to add that feature, I think it would be easier to just add it than integrating with an external app and relying on that ;-)
