### ISSUE TITLE
正则表达式拦截求助

### ISSUE THREAD

**Issue by smdx** [apsun/NekoSMS#43]
最近几天常常收到些xx特码短信，想做个包含某几个字的短信拦截。请教一下要怎么写这个表达式啊？

短信示例：
香港⑥合彩.每期'特'码&包中，欢迎━(*｀∀´*)ノ亻!订阅，打扰了

想要拦截的关键词是同时包含（码和订阅，两个关键词）就拦截。谢谢

**Comment by apsun** [comment]
Try: `码.*订阅|订阅.*码`

**Comment by smdx** [comment]
非常感谢，我试试。
