### ISSUE TITLE
魔趣rom无法正常拦截

### ISSUE THREAD

**Issue by zackga** [apsun/NekoSMS#49]
---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: nx529j
- Android version: 7.1.2
- Xposed version: 4.0.2
- NekoSMS version: 0.16.0

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

01-13 09:37:40.749 I/Xposed  ( 4191): NekoSMS: NekoSMS initializing...
01-13 09:37:40.749 I/Xposed  ( 4191): NekoSMS: Phone manufacturer: nubia
01-13 09:37:40.749 I/Xposed  ( 4191): NekoSMS: Phone model: NX529J
01-13 09:37:40.749 I/Xposed  ( 4191): NekoSMS: Android version: 7.1.2
01-13 09:37:40.750 I/Xposed  ( 4191): NekoSMS: Xposed bridge version: 89
01-13 09:37:40.750 I/Xposed  ( 4191): NekoSMS: NekoSMS version: 0.16.0 (33)
01-13 09:37:40.750 I/Xposed  ( 4191): NekoSMS: Hooking InboundSmsHandler constructor for Android v24+
01-13 09:37:40.863 I/Xposed  ( 4191): NekoSMS: Hooking dispatchIntent() for Android v23+
01-13 09:37:40.865 I/Xposed  ( 4191): NekoSMS: NekoSMS initialization complete!
01-13 09:37:42.594 I/Xposed  ( 4191): NekoSMS: Registering SMS filter content observer
01-13 09:37:42.606 I/Xposed  ( 4191): NekoSMS: Registering app package state receiver
01-13 09:37:42.640 I/Xposed  ( 4191): NekoSMS: Checking if we have OP_WRITE_SMS permission
01-13 09:37:42.641 I/Xposed  ( 4191): NekoSMS: Already have OP_WRITE_SMS permission
04-09 16:42:01.697 I/Xposed  (27685): NekoSMS: Hooking Xposed module status checker
04-09 17:20:45.109 I/Xposed  ( 2978): NekoSMS: Hooking Xposed module status checker
04-09 17:34:44.427 I/XposedInstaller( 6686): Downloaded http://dl.xposed.info/repo/partial/14645.xml.gz with status 0 (error: null), size 25144 bytes
04-09 17:34:44.935 I/XposedInstaller( 6686): Updated repository http://dl.xposed.info/repo/full.xml.gz to version 14675 (18 new / 0 removed modules)
04-09 17:45:14.890 I/Xposed  ( 4191): NekoSMS: Received a new SMS message
04-09 17:45:14.902 I/Xposed  ( 4191): NekoSMS: Sender: "1311***3128"
04-09 17:45:14.902 I/Xposed  ( 4191): NekoSMS: Body: "\u9000\u8ba2\u6d4b\u8bd5"
04-09 17:45:14.911 I/Xposed  ( 4191): NekoSMS: Cached SMS filters dirty, loading from database
04-09 17:45:14.920 I/Xposed  ( 4191): NekoSMS: filterCursor.getCount() = 3
04-09 17:45:14.922 I/Xposed  ( 4191): NekoSMS: Loaded 1 blacklist filters
04-09 17:45:14.922 I/Xposed  ( 4191): NekoSMS: Loaded 2 whitelist filters
04-09 17:45:14.929 I/Xposed  ( 4191): NekoSMS: Allowing message (did not match any rules)

```
Replace this line with your logs. Do not remove the backticks.

使用测试号码发送“退订测试”，黑名单中有“退订”关键字，已关闭联系人白名单，仍然无法正确拦截。!
```
[黑名单截图](https://user-images.githubusercontent.com/38208613/38491660-128e781a-3c1f-11e8-862b-e4d41b22cbd6.png)

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
包含匹配模式不能用`|`代表OR，改成正则表达式就好了
