### ISSUE TITLE
Logo offer for NekoSMS

### ISSUE THREAD

**Issue by familqasimov** [apsun/NekoSMS#51]
Hi sir. I'm graphic designer. I have studied your work and I think a new design will make you more visible. I would like to offer logo. I can give you all the formats of the design free. If you want I send you PR or a change please specify.

![untitled-1](https://user-images.githubusercontent.com/36432269/41253452-71e964e4-6dd1-11e8-8626-8a4406418a02.png)

Best regard
famil

**Comment by apsun** [comment]
Hi, thank you for these designs, they look pretty cool! However, I am not looking for a new logo at this time unfortunately. I really appreciate the effort though!

**Comment by familqasimov** [comment]
Thanks for appreciate. If you ever need a logo then I'll be glad to help
you.

Regards.

12 iyn 2018, Ç.A. 19:02 tarixində Andrew Sun <notifications@github.com>
yazdı:
