### ISSUE TITLE
NekoCall? :3

### ISSUE THREAD

**Issue by HankAviator** [apsun/NekoSMS#53]
This is not an issue report about NekoSMS but suggestion to a new app. I tried to look for a callblocker that works on Oreo with **Xposed** and **regex support** but so far there is none. Maybe it'll be so nice to have a NekoCall with this simple yet powerful feature. 😄 

Edit: the reason is on Oreo the implementation to block a call is different from previous Android releases. To block a call, an app is now required to have root permission (CallerInfo currently doesn't need that though), in addition to that, blocking without letting out any ringtone requires callblocker to be set as main dialer or xposed framework.

**Comment by raamee** [comment]
yes, I second this. There is no proper Xposed module that works with Oreo available now. So, if Neko releases NekoCall, it would be great.

Thank you.

**Comment by apsun** [comment]
Yeahhh... Unfortunately, I've decided that this is probably never going to happen, unfortunately. Sorry. I just don't have the time for it. Seems like a good void for someone else to fill.
