### ISSUE TITLE
Acknowledge message to the SMSC.

### ISSUE THREAD

**Issue by komurlu** [apsun/NekoSMS#55]
Does this app sends or blocks acknowledge message to SMSC when an SMS is blocked?

If "storage full" or such a similar error message is sent to SMSC, sender will not receive a successful delivery receipt, so SMS will be blocked completely.

**Comment by apsun** [comment]
I'm not sure how much of the SMS flow is done by the system; so unfortunately the answer to your question is I don't know.

Are you saying you want delivery receipts to be blocked, or that you want to deliver fake error receipts?

**Comment by komurlu** [comment]
Even if an SMS is blocked, phone sends network ACK that it received SMS successfully and this causes sender to see SMS as delivered. 

I'm trying to find a way to say to the network that phone couldn't handle that last SMS. In this way, sender will not see our blocked SMS as 'successful'.

I'm wondering if  black list controls can be done inside ```dispatchNormalMessage();``` and if message is to be blocked, return   ```Intents.RESULT_SMS_UNSUPPORTED```. Normally it returns  ```android.provider.Telephony.Sms.Intents.RESULT_SMS_HANDLED ``` which causes sending success ACK to the network.

As beginning comments says

```
The state machine starts in {@link IdleState} state. When the {@link SMSDispatcher} receives a
new SMS from the radio, it calls {@link #dispatchNormalMessage},
```

If we return ```Intents.RESULT_SMS_UNSUPPORTED``` before normal return in  ```dispatchNormalMessage();``` , we'll prevent message to be added to the tables, and send error ACK to radio, and hopefully network will not retry sending this SMS.
