### ISSUE TITLE
virtualxposed  support?

### ISSUE THREAD

**Issue by KinaZhen** [apsun/NekoSMS#56]
- Device: 
- Android version: 8.1

我在xposedvirtual中使用，无法正常工作，请问支持吗？

**Comment by apsun** [comment]
From the description of VirtualXposed:

> The only two restriction of VirtualXposed are:
>  Unable to modify system, so any Module which modifies system won't be able to work properly.

NekoSMS modifies system code, so unfortunately it will not work.
