### ISSUE TITLE
希望支持安卓9.0

### ISSUE THREAD

**Issue by klcb2010** [apsun/NekoSMS#58]
现在edxposed盛行，大多数开发者都开始配饰9.0了，特别是重力工具箱已经配饰两个测试版本了。如果需要日志，我来提供。

**Comment by apsun** [comment]
Sorry, I'm not familiar with edxposed, is it a drop-in replacement for the original xposed? If you could somehow get logs that would be great. I'd be willing to update this for Android 9 as long as it doesn't mean rewriting the entire xposed module.

**Comment by apsun** [comment]
I don't see any changes to the InboundSmsHandler class so the module should already work if you can manage to install and activate it, I think..?

**Comment by metaphilium** [comment]
NekoSMS 需要 Xposed （不支持 9.0），目前可以通过太极・Magisk 来实现对 9.0 的支持。

太极项目关于 NekoSMS 的 Issue 是我上个账号提的，前几天注销了所以可能看不到那个 Issue，只需把「电话服务」 （com.android.phone）加入太极并启用 NekoSMS 即可。

**Comment by Youkochan0v0** [comment]
> @metaphilium 一加氧os，安卓p，这样设置了，但仍然拦截不了

太真实了，我以为你是我小号(情况同样，无法拦截)

**Comment by metaphilium** [comment]
@mayziran @Youkochan0v0 

太极・阳、模块引擎、NekoSMS、OOS

可能出问题的就是这几项了，排查一下吧，我 Resurrection Remix OS 上是一切正常的。

**Comment by apsun** [comment]
OxygenOS has some really crappy battery "optimization" feature which is known to break NekoSMS (search previous issues), please add it to the whitelist and see if that helps.

**Comment by mayziran** [comment]
@apsun 已经设置了电池未优化，还是无法拦截

**Comment by apsun** [comment]
Are you able to get a logcat of the problem? You can use `adb logcat -s NekoSMS` on your computer (or you can install MatLog and search for NekoSMS, though you need ADB anyways for that to work)

**Comment by chenyue404** [comment]
edxposd下，可以正常使用啊。

**Comment by mayziran** [comment]
@apsun 好像必须重启手机，重启后可以了，应该是要除了太极添加电话服务以外，必须也要重启手机，之前只重启也没用。

**Comment by LiarOnce** [comment]
It works fine in Android P with EdXposed（Resurrection Remix 7.0.1）
![Screenshot_20190424-095802_EdXposed_Installer.png](https://i.loli.net/2019/04/24/5cbfc2cea30ce.png)
![Screenshot_20190424-095704_NekoSMS.png](https://i.loli.net/2019/04/24/5cbfc2ced56fe.png)

**Comment by xybtc** [comment]
oppo r11什么都设置好了还是无法拦截，用的是官方xposed 89版框架
![Screenshot_2019-05-06-13-14-28-34](https://user-images.githubusercontent.com/50312951/57207589-3fd96200-7001-11e9-81c3-ccb5e5abc91a.png)

**Comment by xybtc** [comment]
> oppo r11什么都设置好了还是无法拦截，用的是官方xposed 89版框架
--------- beginning of crash
--------- beginning of system
--------- beginning of main
05-06 13:13:43.483 24342 24342 I NekoSMS : Hooking Xposed module status checker
05-06 13:14:01.453  2712  2712 I NekoSMS : SMS filter database updated, marking
cache as dirty
05-06 13:14:07.419 24342 24400 I NekoSMS : Export succeeded
05-06 13:14:23.553  2712  2712 I NekoSMS : SMS filter database updated, marking
cache as dirty

> ![Screenshot_2019-05-06-13-14-28-34](https://user-images.githubusercontent.com/50312951/57207589-3fd96200-7001-11e9-81c3-ccb5e5abc91a.png)

**Comment by fcying** [comment]
1+6T 配合太极工作正常

**Comment by Qingyunruooyu** [comment]
用楼上那个V0.3.1.7beta版本的EdXposed就可以啦，之前用的老版本就不行
