### ISSUE TITLE
三星S8+，Android P，拦截失败

### ISSUE THREAD

**Issue by VickyRain** [apsun/NekoSMS#70]
三星S8+，Android P最新固件底包+极光系统，NekoSMS拦截失败。
不过不仅仅是NekoSMS拦截短信失败，三星系统自带的拦截软件/腾讯手机管家/360手机卫士等等软件也一样拦截失败。
非常奇怪，其实腾讯/360都能监听到短信送达的广播并且显示在自己的拦截列表里，但是似乎是试图删除系统/data/user_de/0/com.android.providers.telephony/databases/mmssms.db的数据（直接看/data/data/com.android.providers.telephony是看不到databases的，Android多用户的原因？）不成功，导致默认短信APP还是显示了应该被拦截的信息。
但是三星自带的拦截APP和NekoSMS则是看不到有被拦截的记录，机制不一样？

**Comment by apsun** [comment]
Sorry I can't diagnose this without Xposed logs (please follow the issue template). I also have never tested NekoSMS with multi-user, so I can't say whether that matters.

**Comment by VickyRain** [comment]
EdXposed内没有NekoSMS的Logs显示，详细log模式已经打开（EdXposed内Vervbose Logs也是空的，并且不仅是NekoSMS没有，其他模块也没有，真的是很奇怪的一件事），所以没有能导出来的内容。
我的手机上现在只有一个用户……
p.s.太极这里打开就闪退，所以没试过配合太极使用。

**Comment by apsun** [comment]
You can get logs by connecting your phone to your computer and running `adb logcat -s NekoSMS` too. (You'll have to download the Android SDK tools to get adb)

**Comment by VickyRain** [comment]
还是没有日志输出。我用命令行和IDEA都看过Logcat了，用“NekoSMS”过滤没有显示任何信息，非Xposed模块的APP日志打印都是OK的。
EdXposed框架整个日志输出都失败了，打开它的日志显示：Cannot read log /data/user_de/0/com.solohsu.android.edxp.manager/log/error.log (No such file or directory)
我看了手机里，com.solohsu.android.edxp.manager下没有log文件夹，只有cache、code_cache、files、no_backup、shared_prefs。

**Comment by VickyRain** [comment]
换EdXposed Manager以后好使了>o<
