### ISSUE TITLE
推荐的作用域是哪几个APP?

### ISSUE THREAD

**Issue by entr0pia** [apsun/NekoSMS#74]

**Comment by apsun** [comment]
Sorry, I don't understand your question. What are you asking for specifically?

**Comment by entr0pia** [comment]
> Sorry, I don't understand your question. What are you asking for specifically?

In a global whitelist mode, which applications should the NekoSMS be enabled for?

**Comment by apsun** [comment]
NekoSMS does not have the concept of being enabled for certain apps; it is either on or off globally, so I'm still confused what you are asking for.

**Comment by entr0pia** [comment]
> NekoSMS does not have the concept of being enabled for certain apps; it is either on or off globally, so I'm still confused what you are asking for.

Ok. Look at this picture, it's a Xposed manager: LSPosed. The NekoSMS will take effect on the ticked apps. So, which apps need to be ticked?
![1617423477423](https://user-images.githubusercontent.com/30486766/113467619-b8a7f980-9476-11eb-9b86-3bb84320a387.png)

**Comment by apsun** [comment]
Oh, `com.android.phone` and `com.crossbowffs.nekosms` are the only two you need. Sorry I didn't know Xposed-compatible frameworks these days let you choose which packages to hook.

**Comment by entr0pia** [comment]
> Oh, `com.android.phone` and `com.crossbowffs.nekosms` are the only two you need. Sorry I didn't know Xposed-compatible frameworks these days let you choose which packages to hook.

Thanks
