### ISSUE TITLE
Lsposed support

### ISSUE THREAD

**Issue by stlion** [apsun/NekoSMS#75]
建议配合LSPOSED，添加作用域的自动告知。

**Comment by apsun** [comment]
[According to their repo](https://github.com/LSPosed/LSPosed#for-developers), LSPosed is compatible with Xposed modules, so I don't understand what you want me to do. If you tried it and it doesn't work, please post your logs.

**Comment by stlion** [comment]
![fcoolapk](https://user-images.githubusercontent.com/9400418/114827416-3e269480-9dfb-11eb-8b9d-6c9555c78459.jpg)
例如，f***coolapk会跟lsposed声明是作用于coolapk这个软件，在lsposed内会明确标示出来。建议NekoSMS也可以添加，方便也cool（虽然我也会去看README.md去手动选作用域）。

**Comment by apsun** [comment]
Oh I see, you're referring to https://github.com/LSPosed/LSPosed/wiki/Module-Scope

Sure, I can add this.

**Comment by Abdullah-Haque** [comment]
@apsun Did u get it to work on android 11 lsposed ....I am using samsung A50 one ui 3.1 and activated phone and messaging apps but still not blocking...using latest neko sms with latest riru core and lsposed...
