### ISSUE TITLE
使用白名单拦截功能失效

### ISSUE THREAD

**Issue by 262379** [apsun/NekoSMS#95]
Write your issue description here.

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: oneplus 8t
- Android version: Android13 pixel experience plus
- Xposed version: lsposed zygisk 1.8.6（6900）
- NekoSMS version: 0.21.0（40）
Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:
[LSPosed_2023-05-31T18_05_44.786158.zip](https://github.com/apsun/NekoSMS/files/11611730/LSPosed_2023-05-31T18_05_44.786158.zip)

```
Replace this line with your logs. Do not remove the backticks.
```

Thank you for helping us help you help us all.

**Comment by 262379** [comment]
使用的是白名单里的文本匹配正则表达式

**Comment by apsun** [comment]
What is your pattern?

**Comment by apsun** [comment]
Your filter rules start with `|`. A rule of `|x|y|z` means, match *nothing*, or `x`, or `y`, or `z`. Every message contains *nothing*, so this will match every message. See https://regex101.com/r/ziTCSy/1 for example.

Just delete the `|` in front to fix this. `|x|y|z` -> `x|y|z`

**Comment by 262379** [comment]
好的已解决谢谢
