### ISSUE TITLE
模块在Android 14正式版不生效

### ISSUE THREAD

**Issue by zyh941** [apsun/NekoSMS#98]
Write your issue description here.
开发者你好，我前两天把Pixel 5从13升级到最新的正式版Android 14了，模块能打开，但是不能成功拦截含黑名单文本的短信，请检查、修复一下吧，附上截图：
![Screenshot_20231012-082656](https://github.com/apsun/NekoSMS/assets/95530307/dd591715-ade8-44e7-89d0-266813c1976d)
![Screenshot_20231012-082702](https://github.com/apsun/NekoSMS/assets/95530307/0c0084b2-3e0d-4cb1-8c72-2df39c375e89)
![Screenshot_20231012-082733](https://github.com/apsun/NekoSMS/assets/95530307/be14becb-3c4f-4d7e-b8ad-d265b4a89ca6)

---

**If you are submitting a bug report and do not include the following info, your issue will be ignored!**

- Device: Google Pixel 5
- Android version: 14 stock stable (UP1A.231005.007)
- Xposed version: LSPosed stable 1.9.2 (7024)
- NekoSMS version: 0.21.0 (40)

Please paste your Xposed logs (Xposed Installer -> Logs -> Menu -> Save to SD card) below:

```
[LSPosed_2023-10-12T08_38_42.027670.zip](https://github.com/apsun/NekoSMS/files/12875856/LSPosed_2023-10-12T08_38_42.027670.zip)

```

Thank you for helping us help you help us all.

**Comment by apsun** [comment]
I believe https://github.com/apsun/NekoSMS/commit/b8f0bd6879700c4e032899c839e69ffba15d778b should fix this, mind giving this build a try?

[app-release.apk.zip](https://github.com/apsun/NekoSMS/files/12902387/app-release.apk.zip)

**Comment by zyh941** [comment]
> I believe [b8f0bd6](https://github.com/apsun/NekoSMS/commit/b8f0bd6879700c4e032899c839e69ffba15d778b) should fix this, mind giving this build a try?
> 
> [app-release.apk.zip](https://github.com/apsun/NekoSMS/files/12902387/app-release.apk.zip)

用收取验证码为黑名单测试，已成功拦截
